name: maida_coffee_challenge
description: No description, at the moment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    - assets/images/chef.png
    - assets/images/avatar.png
    - assets/images/cuscuz_simples.png
    - assets/images/cuscuz_completo.png
    - assets/images/lingua_sogra_pq.png
    - assets/images/lingua_sogra_gr.png
    - assets/images/pao_caseiro.png
    - assets/images/pao_caseiro_completo.png
    - assets/images/misto_quente.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700